import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { resolve } from 'path'

// manually parse .env.local
const envPath = resolve(__dirname, '../.env.local')
const envContent = readFileSync(envPath, 'utf-8')
for (const line of envContent.split('\n')) {
  const [key, ...rest] = line.split('=')
  if (key && rest.length) process.env[key.trim()] = rest.join('=').trim()
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } },
)

const products = [
  {
    name: 'Basmati Rice',
    slug: 'basmati-rice',
    category: 'Grains',
    tagline: 'Premium long-grain aromatic rice',
    short_description: 'World-renowned for its distinctive fragrance, long grains, and fluffy texture after cooking.',
    origin: 'India',
    emoji: '🍚',
    accent_color: '#C8882A',
    images: [{ url: '/products/basmati-rice.png', alt: 'Basmati Rice' }],
    varieties: ['1121 Basmati', 'Traditional Basmati', 'Pusa Basmati', 'Sugandha Basmati'],
    grades: ['Premium', 'Grade A', 'Grade B'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', 'Custom Packaging'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000'],
    use_cases: ['Fine Dining', 'Biryani', 'Pilaf', 'Export Markets'],
    availability: 'Year-round',
    moq: '1',
    moq_unit: 'Container Load',
    display_order: 1,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Turmeric',
    slug: 'turmeric',
    category: 'Spices',
    tagline: 'Golden spice of life',
    short_description: 'High-curcumin turmeric sourced from the finest farms in India, ideal for food, cosmetics, and pharmaceuticals.',
    origin: 'India',
    emoji: '🌿',
    accent_color: '#E8A020',
    images: [
      { url: '/products/turmeric.png', alt: 'Turmeric' },
      { url: '/products/turmeric-hero.png', alt: 'Turmeric Hero' },
    ],
    varieties: ['Erode Turmeric', 'Salem Turmeric', 'Nizamabad Turmeric', 'Alleppey Finger'],
    grades: ['Double Polished', 'Single Polished', 'Unpolished', 'Powder'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', 'Bulk'],
    certifications: ['APEDA', 'FSSAI', 'Organic Certified'],
    use_cases: ['Food Industry', 'Pharmaceuticals', 'Cosmetics', 'Ayurveda'],
    availability: 'Year-round',
    moq: '5',
    moq_unit: 'MT',
    display_order: 2,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Cumin Seeds',
    slug: 'cumin-seeds',
    category: 'Spices',
    tagline: 'Earthy aroma, rich flavour',
    short_description: 'Premium quality cumin seeds with high volatile oil content, widely used in cuisines and Ayurvedic medicine.',
    origin: 'India',
    emoji: '🌾',
    accent_color: '#8B6914',
    images: [{ url: '/products/cumin-seeds.png', alt: 'Cumin Seeds' }],
    varieties: ['Gujarat Cumin', 'Rajasthan Cumin'],
    grades: ['Grade A', 'Grade B', 'Machine Clean', 'Sortex Clean'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', 'Bulk'],
    certifications: ['APEDA', 'FSSAI', 'ISO 9001'],
    use_cases: ['Food Processing', 'Spice Blends', 'Pharmaceutical', 'Essential Oil Extraction'],
    availability: 'May – September',
    moq: '5',
    moq_unit: 'MT',
    display_order: 3,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Sesame Seeds',
    slug: 'sesame-seeds',
    category: 'Oil Seeds',
    tagline: 'Nature\'s tiny powerhouse',
    short_description: 'High-oil content sesame seeds in natural, hulled, and roasted varieties for global food and oil industries.',
    origin: 'India',
    emoji: '🌻',
    accent_color: '#C4A35A',
    images: [{ url: '/products/sesame-seeds.png', alt: 'Sesame Seeds' }],
    varieties: ['Natural White', 'Hulled', 'Roasted', 'Black Sesame'],
    grades: ['99.98% Purity', '99.95% Purity', 'FAQ'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', '1 MT Jumbo Bags'],
    certifications: ['APEDA', 'FSSAI', 'Halal', 'Kosher'],
    use_cases: ['Oil Extraction', 'Bakery', 'Confectionery', 'Tahini Production'],
    availability: 'Year-round',
    moq: '5',
    moq_unit: 'MT',
    display_order: 4,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Red Chilli',
    slug: 'red-chilli',
    category: 'Spices',
    tagline: 'Bold heat, vibrant colour',
    short_description: 'Premium dried red chillies with high pungency and rich colour, sourced from Andhra Pradesh and Telangana.',
    origin: 'India',
    emoji: '🌶️',
    accent_color: '#C0392B',
    images: [{ url: '/products/red-chilli.png', alt: 'Red Chilli' }],
    varieties: ['Teja', 'Guntur Sannam', 'Byadgi', 'Kashmiri'],
    grades: ['S4', 'S6', 'S8', 'S10', 'S17'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', 'Bulk'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000'],
    use_cases: ['Spice Industry', 'Food Processing', 'Sauce & Condiments', 'Powder Production'],
    availability: 'Year-round',
    moq: '5',
    moq_unit: 'MT',
    display_order: 5,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Groundnuts',
    slug: 'groundnuts',
    category: 'Oil Seeds',
    tagline: 'Superior quality peanuts',
    short_description: 'Bold and Java peanuts with high oil content, suitable for direct consumption, oil extraction, and peanut butter.',
    origin: 'India',
    emoji: '🥜',
    accent_color: '#A0522D',
    images: [{ url: '/products/groundnuts.png', alt: 'Groundnuts' }],
    varieties: ['Bold (Runner)', 'Java (Spanish)', 'Red Skin', 'Blanched'],
    grades: ['40/50', '50/60', '60/70', '70/80 Count'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', '1 MT Jumbo Bags'],
    certifications: ['APEDA', 'FSSAI', 'Aflatoxin Free'],
    use_cases: ['Oil Extraction', 'Peanut Butter', 'Confectionery', 'Snack Industry'],
    availability: 'Year-round',
    moq: '5',
    moq_unit: 'MT',
    display_order: 6,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Wheat',
    slug: 'wheat',
    category: 'Grains',
    tagline: 'Premium Indian wheat',
    short_description: 'High protein wheat varieties ideal for flour milling, bread making, and pasta production.',
    origin: 'India',
    emoji: '🌾',
    accent_color: '#D4A843',
    images: [{ url: '/products/wheat.png', alt: 'Wheat' }],
    varieties: ['Sharbati', 'Milling Wheat', 'Durum Wheat', 'HI-8498'],
    grades: ['FAQ', 'Grade A', 'Milling Grade'],
    packaging: ['50 Kg PP Bags', '1 MT Jumbo Bags', 'Bulk Vessel'],
    certifications: ['APEDA', 'FSSAI', 'ISO 9001'],
    use_cases: ['Flour Milling', 'Bread Industry', 'Pasta Production', 'Animal Feed'],
    availability: 'April – August',
    moq: '1',
    moq_unit: 'Container Load',
    display_order: 7,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Soybean',
    slug: 'soybean',
    category: 'Oil Seeds',
    tagline: 'Protein-rich, versatile oilseed',
    short_description: 'Non-GMO soybeans with high protein content for oil extraction, meal production, and food processing.',
    origin: 'India',
    emoji: '🫘',
    accent_color: '#6B8E23',
    images: [{ url: '/products/soybean.png', alt: 'Soybean' }],
    varieties: ['Non-GMO Soybean', 'Food Grade', 'Feed Grade'],
    grades: ['FAQ', 'Grade A'],
    packaging: ['50 Kg PP Bags', '1 MT Jumbo Bags', 'Bulk'],
    certifications: ['APEDA', 'FSSAI', 'Non-GMO Certified'],
    use_cases: ['Oil Extraction', 'Soy Meal', 'Food Processing', 'Animal Feed'],
    availability: 'October – February',
    moq: '1',
    moq_unit: 'Container Load',
    display_order: 8,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Coriander Seeds',
    slug: 'coriander-seeds',
    category: 'Spices',
    tagline: 'Aromatic & versatile spice',
    short_description: 'Whole and split coriander seeds with rich citrus flavour, used in spice blends, essential oil, and cooking.',
    origin: 'India',
    emoji: '🌿',
    accent_color: '#7BA05B',
    images: [{ url: '/products/coriander-seeds.png', alt: 'Coriander Seeds' }],
    varieties: ['Eagle (Split)', 'Scooter (Whole)', 'Badami'],
    grades: ['Machine Clean', 'Sortex Clean', 'FAQ'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags'],
    certifications: ['APEDA', 'FSSAI'],
    use_cases: ['Spice Blends', 'Essential Oil Extraction', 'Cooking', 'Herbal Medicine'],
    availability: 'Year-round',
    moq: '5',
    moq_unit: 'MT',
    display_order: 9,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Garlic',
    slug: 'garlic',
    category: 'Fresh Vegetables',
    tagline: 'Pungent, flavourful, and nutritious',
    short_description: 'Premium fresh garlic with high allicin content, available in raw, peeled, and dehydrated forms.',
    origin: 'India',
    emoji: '🧄',
    accent_color: '#E8D5A3',
    images: [{ url: '/products/garlic.png', alt: 'Garlic' }],
    varieties: ['Single Clove (Mahua)', 'Multi Clove', 'Purple Stripe'],
    grades: ['50–60 mm', '60–70 mm', '70+ mm', 'Loose Mesh'],
    packaging: ['10 Kg Mesh Bags', '20 Kg Mesh Bags', '1 MT Jumbo Bags'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certified'],
    use_cases: ['Food Industry', 'Pharmaceutical', 'Dehydration Industry', 'Retail'],
    availability: 'February – June',
    moq: '5',
    moq_unit: 'MT',
    display_order: 10,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Red Onion',
    slug: 'red-onion',
    category: 'Fresh Vegetables',
    tagline: 'India\'s finest export onion',
    short_description: 'Premium red onions with tight skin, pungent flavour, and excellent shelf life for global markets.',
    origin: 'India',
    emoji: '🧅',
    accent_color: '#8B1A4A',
    images: [{ url: '/products/red-onion.png', alt: 'Red Onion' }],
    varieties: ['Nashik Red', 'Bellary Red', 'Bangalore Rose'],
    grades: ['35–55 mm', '45–65 mm', '55–75 mm', '65–80 mm'],
    packaging: ['20 Kg Mesh Bags', '25 Kg PP Bags', 'Loose Bulk'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certified'],
    use_cases: ['Retail Supermarkets', 'Food Processing', 'Dehydration', 'Catering'],
    availability: 'October – May',
    moq: '1',
    moq_unit: 'Container Load',
    display_order: 11,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Ginger',
    slug: 'ginger',
    category: 'Fresh Vegetables',
    tagline: 'Zingy, fresh, and potent',
    short_description: 'Fresh and dried ginger with high gingerol content for food, beverage, and pharmaceutical applications.',
    origin: 'India',
    emoji: '🫚',
    accent_color: '#C8962A',
    images: [{ url: '/products/ginger.png', alt: 'Ginger' }],
    varieties: ['Fresh Ginger', 'Dry Ginger', 'Bleached Ginger'],
    grades: ['FAQ', 'Grade A', 'Export Quality'],
    packaging: ['20 Kg Mesh Bags', '50 Kg Jute Bags', 'Bulk'],
    certifications: ['APEDA', 'FSSAI', 'Organic Available'],
    use_cases: ['Food & Beverage', 'Pharmaceutical', 'Essential Oil', 'Ayurveda'],
    availability: 'February – May',
    moq: '5',
    moq_unit: 'MT',
    display_order: 12,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Mustard Seeds',
    slug: 'mustard-seeds',
    category: 'Oil Seeds',
    tagline: 'Small seed, big impact',
    short_description: 'Yellow and black mustard seeds with high oil content, ideal for oil extraction and condiment production.',
    origin: 'India',
    emoji: '🌱',
    accent_color: '#C8A000',
    images: [{ url: '/products/mustard-seeds.png', alt: 'Mustard Seeds' }],
    varieties: ['Yellow Mustard', 'Black Mustard', 'Brown Mustard'],
    grades: ['99.5% Purity', '99% Purity', 'FAQ'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', '1 MT Jumbo Bags'],
    certifications: ['APEDA', 'FSSAI'],
    use_cases: ['Oil Extraction', 'Mustard Sauce', 'Pickling', 'Spice Blends'],
    availability: 'March – June',
    moq: '5',
    moq_unit: 'MT',
    display_order: 13,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Pulses & Lentils',
    slug: 'pulses-lentils',
    category: 'Pulses',
    tagline: 'Nutritious legumes for every market',
    short_description: 'A wide range of high-protein pulses and lentils including chana, moong, masoor, and toor dal.',
    origin: 'India',
    emoji: '🫘',
    accent_color: '#C47A2A',
    images: [{ url: '/products/pulses-lentils.png', alt: 'Pulses & Lentils' }],
    varieties: ['Chana Dal', 'Moong Dal', 'Masoor Dal', 'Toor Dal', 'Urad Dal', 'Kabuli Chana'],
    grades: ['Machine Clean', 'Sortex Clean', 'FAQ'],
    packaging: ['25 Kg PP Bags', '50 Kg Jute Bags', '1 MT Jumbo Bags'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000'],
    use_cases: ['Food Industry', 'Retail', 'Dal Mills', 'Flour Production'],
    availability: 'Year-round',
    moq: '5',
    moq_unit: 'MT',
    display_order: 14,
    is_published: true,
    is_future: false,
  },
]

async function seed() {
  console.log(`Seeding ${products.length} products…`)

  const { data: existing } = await supabase
    .from('products')
    .select('slug')

  const existingSlugs = new Set((existing ?? []).map((p: { slug: string }) => p.slug))
  const toInsert = products.filter((p) => !existingSlugs.has(p.slug))

  if (toInsert.length === 0) {
    console.log('All products already exist. Nothing to insert.')
    return
  }

  const { error } = await supabase.from('products').insert(toInsert)

  if (error) {
    console.error('Insert failed:', error.message)
    process.exit(1)
  }

  console.log(`✓ Inserted ${toInsert.length} products.`)
  if (toInsert.length < products.length) {
    console.log(`Skipped ${products.length - toInsert.length} already-existing products.`)
  }
}

seed()
