// scripts/seed.ts
// Run with: npx tsx --env-file=.env.local scripts/seed.ts
import { createClient } from '@supabase/supabase-js'
import type { Database } from '../src/types/database'

const supabase = createClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

type SeedProduct = {
  name: string
  slug: string
  category: string
  tagline?: string
  short_description?: string
  full_description?: string
  origin?: string
  emoji?: string
  accent_color?: string
  varieties?: string[]
  grades?: string[]
  packaging?: string[]
  certifications?: string[]
  use_cases?: string[]
  related_slugs?: string[]
  specs?: { label: string; value: string }[]
  availability?: string
  moq?: string
  moq_unit?: 'Kg' | 'MT' | 'Container Load' | 'Custom'
  display_order: number
  is_published: boolean
  is_future: boolean
}

const products: SeedProduct[] = [
  // ==================== FRESH VEGETABLES ====================
  {
    name: 'Fresh Red Onion',
    slug: 'fresh-red-onion',
    category: 'Fresh Vegetables',
    tagline: "India's most exported vegetable.",
    short_description: 'Farm-fresh red onions from Nashik, firm-skinned and built for long-haul export.',
    full_description: "Nashik, Maharashtra is India's onion capital, supplying over 30% of the country's production. Our fresh red onions are carefully selected for firmness, low-moisture skin, and extended shelf life under ambient storage conditions. All shipments carry phytosanitary certificates and are fumigation-treated on request.",
    origin: 'Nashik, Maharashtra & Bangalore Rural, Karnataka',
    emoji: '🧅',
    accent_color: '#C0392B',
    varieties: ['Red Onion', 'Pink Onion', 'White Onion'],
    grades: ['Small', 'Medium', 'Large', 'Premium Export Quality'],
    packaging: ['5 Kg Mesh Bag', '10 Kg Mesh Bag', '25 Kg Mesh Bag', '50 Kg Mesh Bag', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate', 'Non-GMO'],
    use_cases: ['Retail grocery', 'Food processing', 'Dehydration industry', 'Condiment production', 'Restaurant supply'],
    related_slugs: ['fresh-garlic', 'fresh-ginger', 'fresh-green-chilli'],
    availability: 'Year-round',
    moq: '1',
    moq_unit: 'MT',
    display_order: 1,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh White Onion',
    slug: 'fresh-white-onion',
    category: 'Fresh Vegetables',
    tagline: 'Mild, crisp, and export-clean.',
    short_description: 'Fresh white onions with mild flavour, preferred for international processing markets.',
    origin: 'Nashik, Maharashtra & Rajasthan',
    emoji: '⬜',
    accent_color: '#E0D5C5',
    varieties: ['White Onion'],
    grades: ['Small', 'Medium', 'Large', 'Premium Export Quality'],
    packaging: ['5 Kg Mesh Bag', '10 Kg Mesh Bag', '25 Kg Mesh Bag', '50 Kg Mesh Bag', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    use_cases: ['Food processing', 'Condiment production', 'Dehydration industry'],
    related_slugs: ['fresh-red-onion', 'fresh-pink-onion'],
    availability: 'Year-round',
    moq: '1',
    moq_unit: 'MT',
    display_order: 2,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Pink Onion',
    slug: 'fresh-pink-onion',
    category: 'Fresh Vegetables',
    short_description: 'Tender pink onions with balanced sweetness and pungency.',
    origin: 'Nashik, Maharashtra',
    emoji: '🌸',
    accent_color: '#E8A0B0',
    grades: ['Small', 'Medium', 'Large'],
    packaging: ['5 Kg Mesh Bag', '10 Kg Mesh Bag', '25 Kg Mesh Bag', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    related_slugs: ['fresh-red-onion', 'fresh-white-onion'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 3,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Garlic',
    slug: 'fresh-garlic',
    category: 'Fresh Vegetables',
    tagline: 'Strong pungency. Export-ready.',
    short_description: 'Fresh Indian garlic with high allicin content, graded and cleaned for export.',
    full_description: "India is among the world's top garlic exporters with Madhya Pradesh and Rajasthan as primary producing states. Our garlic is carefully graded by bulb size, cleaned and dried to export standards, and packed to withstand long-haul freight.",
    origin: 'Madhya Pradesh & Rajasthan, India',
    emoji: '🧄',
    accent_color: '#C8882A',
    varieties: ['Indian Garlic', 'Premium Garlic'],
    grades: ['Small', 'Medium', 'Large'],
    packaging: ['5 Kg Mesh Bag', '10 Kg Mesh Bag', '20 Kg Mesh Bag', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate', 'Non-GMO', 'Halal'],
    use_cases: ['Food processing', 'Condiment manufacturing', 'Dehydration & powder', 'Retail grocery', 'Pharmaceutical'],
    related_slugs: ['fresh-red-onion', 'fresh-ginger'],
    availability: 'November – April',
    moq: '1',
    moq_unit: 'MT',
    display_order: 4,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Ginger',
    slug: 'fresh-ginger',
    category: 'Fresh Vegetables',
    tagline: 'High oleoresin. Full-spectrum heat.',
    short_description: 'Export-grade fresh ginger with high gingerol content from Kerala and Northeast India.',
    full_description: "Kerala's Wayanad and Northeast India's Meghalaya produce ginger with the highest volatile oil and oleoresin content globally. We supply fresh ginger with gingerol content certified for nutraceutical and food-grade applications. Fumigation-free options available.",
    origin: 'Wayanad, Kerala & Meghalaya, Northeast India',
    emoji: '🫚',
    accent_color: '#C07830',
    varieties: ['Fresh Ginger', 'Organic Ginger'],
    grades: ['Standard', 'Premium'],
    packaging: ['5 Kg Box', '10 Kg Box', '25 Kg Bag', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'Organic', 'Halal', 'Kosher'],
    use_cases: ['Beverages & teas', 'Bakery & confectionery', 'Nutraceuticals', 'Pharmaceutical', 'Oleoresin extraction'],
    related_slugs: ['turmeric-finger', 'fresh-garlic'],
    availability: 'Year-round',
    moq: '500',
    moq_unit: 'Kg',
    display_order: 5,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Potato',
    slug: 'fresh-potato',
    category: 'Fresh Vegetables',
    short_description: 'Farm-fresh potatoes from Agra and UP, export-graded for size and dry matter.',
    origin: 'Agra, Uttar Pradesh & Punjab, India',
    emoji: '🥔',
    accent_color: '#C8A87A',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    related_slugs: ['fresh-red-onion', 'fresh-tomato'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 6,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Tomato',
    slug: 'fresh-tomato',
    category: 'Fresh Vegetables',
    short_description: 'Firm, export-grade tomatoes from Andhra Pradesh and Karnataka.',
    origin: 'Andhra Pradesh & Karnataka, India',
    emoji: '🍅',
    accent_color: '#E53935',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    related_slugs: ['fresh-red-onion', 'fresh-potato'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 7,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Green Chilli',
    slug: 'fresh-green-chilli',
    category: 'Fresh Vegetables',
    short_description: 'Pungent green chillies from Andhra Pradesh, export-sorted for size and heat.',
    origin: 'Andhra Pradesh & Telangana, India',
    emoji: '🌶️',
    accent_color: '#388E3C',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    related_slugs: ['red-chilli', 'fresh-red-onion'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 8,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Okra (Lady Finger)',
    slug: 'fresh-okra',
    category: 'Fresh Vegetables',
    short_description: 'Tender, export-grade okra sourced from Gujarat and Maharashtra.',
    origin: 'Gujarat & Maharashtra, India',
    emoji: '🌿',
    accent_color: '#4CAF50',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 9,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Brinjal (Eggplant)',
    slug: 'fresh-brinjal',
    category: 'Fresh Vegetables',
    short_description: 'Purple and green brinjal varieties, export-graded and packed for long-haul.',
    origin: 'Maharashtra & Andhra Pradesh, India',
    emoji: '🍆',
    accent_color: '#6A1B9A',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 10,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Cabbage',
    slug: 'fresh-cabbage',
    category: 'Fresh Vegetables',
    short_description: 'Firm, compact cabbages export-cleaned and packed for international markets.',
    origin: 'Maharashtra & Karnataka, India',
    emoji: '🥬',
    accent_color: '#66BB6A',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 11,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Cauliflower',
    slug: 'fresh-cauliflower',
    category: 'Fresh Vegetables',
    short_description: 'Export-grade cauliflower with tight curd and extended shelf life.',
    origin: 'Punjab, Haryana & Maharashtra, India',
    emoji: '🥦',
    accent_color: '#F5F5F5',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 12,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Carrot',
    slug: 'fresh-carrot',
    category: 'Fresh Vegetables',
    short_description: 'Bright orange carrots from Punjab and Rajasthan, export-washed and graded.',
    origin: 'Punjab & Rajasthan, India',
    emoji: '🥕',
    accent_color: '#FF7043',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 13,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Beetroot',
    slug: 'fresh-beetroot',
    category: 'Fresh Vegetables',
    short_description: 'Deep red beetroots with high sugar content, export-graded from Maharashtra.',
    origin: 'Maharashtra & Karnataka, India',
    emoji: '🟣',
    accent_color: '#880E4F',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 14,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Bottle Gourd',
    slug: 'fresh-bottle-gourd',
    category: 'Fresh Vegetables',
    short_description: 'Tender bottle gourds from UP and Maharashtra, export-packed for freshness.',
    origin: 'Uttar Pradesh & Maharashtra, India',
    emoji: '🥒',
    accent_color: '#81C784',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 15,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Bitter Gourd',
    slug: 'fresh-bitter-gourd',
    category: 'Fresh Vegetables',
    short_description: 'Premium bitter gourds with high medicinal value, export-sorted and packed.',
    origin: 'Andhra Pradesh & Karnataka, India',
    emoji: '🌿',
    accent_color: '#558B2F',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 16,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Ridge Gourd',
    slug: 'fresh-ridge-gourd',
    category: 'Fresh Vegetables',
    short_description: 'Fresh ridge gourds export-graded for length and freshness.',
    origin: 'Maharashtra & Andhra Pradesh, India',
    emoji: '🌿',
    accent_color: '#66BB6A',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 17,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Drumstick (Moringa)',
    slug: 'fresh-drumstick',
    category: 'Fresh Vegetables',
    short_description: 'High-demand moringa drumsticks from Tamil Nadu, packed for export.',
    origin: 'Tamil Nadu & Andhra Pradesh, India',
    emoji: '🪵',
    accent_color: '#8D6E63',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate', 'Organic (select lots)'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 18,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Green Peas',
    slug: 'fresh-green-peas',
    category: 'Fresh Vegetables',
    short_description: 'Tender green peas from Punjab and UP, export-packed in breathable bags.',
    origin: 'Punjab & Uttar Pradesh, India',
    emoji: '🫛',
    accent_color: '#4CAF50',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 19,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Capsicum',
    slug: 'fresh-capsicum',
    category: 'Fresh Vegetables',
    short_description: 'Colourful export-grade capsicum — red, green, and yellow — from Maharashtra.',
    origin: 'Maharashtra & Himachal Pradesh, India',
    emoji: '🫑',
    accent_color: '#E53935',
    varieties: ['Green Capsicum', 'Red Capsicum', 'Yellow Capsicum'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 20,
    is_published: true,
    is_future: false,
  },

  // ==================== FRESH FRUITS ====================
  {
    name: 'Fresh Mango',
    slug: 'fresh-mango',
    category: 'Fresh Fruits',
    tagline: 'The king of fruits. Export-ready.',
    short_description: 'Premium Alphonso, Kesar, and Banganapalli mangoes packed for air and sea freight.',
    full_description: "India is the world's largest mango producer. We export Alphonso (GI-tagged, Maharashtra), Kesar (Gujarat), and Banganapalli (Andhra Pradesh) varieties packed in ventilated corrugated export boxes with ethylene-absorbing sachets for extended shelf life.",
    origin: 'Ratnagiri, Maharashtra & Junagadh, Gujarat',
    emoji: '🥭',
    accent_color: '#FF8F00',
    varieties: ['Alphonso', 'Kesar', 'Banganapalli'],
    grades: ['Premium', 'Standard'],
    packaging: ['Corrugated Export Boxes', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate', 'EU-MRL Compliant'],
    use_cases: ['Retail grocery', 'Juice processing', 'Pulp manufacturing', 'Food service'],
    related_slugs: ['fresh-pomegranate', 'fresh-banana'],
    availability: 'April – July',
    moq: '1',
    moq_unit: 'MT',
    display_order: 21,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Pomegranate',
    slug: 'fresh-pomegranate',
    category: 'Fresh Fruits',
    tagline: "Bhagwa's ruby red arils. World-class.",
    short_description: 'Bhagwa and Ganesh variety pomegranates from Solapur, in corrugated export boxes.',
    full_description: "Solapur, Maharashtra produces over 60% of India's pomegranate crop. The Bhagwa variety — with its deep ruby-red arils, sweet-tart flavour, and long shelf life — is the preferred export variety for Gulf, European, and Southeast Asian markets.",
    origin: 'Solapur, Maharashtra & Bijapur, Karnataka',
    emoji: '🍎',
    accent_color: '#C62828',
    varieties: ['Bhagwa', 'Ganesh'],
    grades: ['Premium', 'Standard'],
    packaging: ['Corrugated Export Boxes', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate', 'GlobalG.A.P. (select lots)'],
    use_cases: ['Retail grocery', 'Juice processing', 'Functional food', 'Arils for food service'],
    related_slugs: ['fresh-mango', 'fresh-grapes'],
    availability: 'October – February',
    moq: '1',
    moq_unit: 'MT',
    display_order: 22,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Grapes',
    slug: 'fresh-grapes',
    category: 'Fresh Fruits',
    short_description: 'Thompson Seedless and Sharad Seedless grapes from Nashik, export-packed.',
    origin: 'Nashik, Maharashtra & Sangli, Maharashtra',
    emoji: '🍇',
    accent_color: '#6A1B9A',
    varieties: ['Thompson Seedless', 'Sharad Seedless', 'Red Globe'],
    packaging: ['4 Kg Punnet Box', '8 Kg Export Box', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'EU-MRL Compliant', 'GlobalG.A.P.'],
    availability: 'January – May',
    moq: '1',
    moq_unit: 'MT',
    display_order: 23,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Banana',
    slug: 'fresh-banana',
    category: 'Fresh Fruits',
    short_description: 'Cavendish and Robusta bananas from Tamil Nadu and Maharashtra.',
    origin: 'Tamil Nadu & Maharashtra, India',
    emoji: '🍌',
    accent_color: '#F9A825',
    varieties: ['Cavendish', 'Robusta', 'Nendran'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'Year-round',
    moq: '1',
    moq_unit: 'MT',
    display_order: 24,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Orange',
    slug: 'fresh-orange',
    category: 'Fresh Fruits',
    short_description: 'Nagpur Santra oranges with high juice content, export-graded.',
    origin: 'Nagpur, Maharashtra & Vidarbha region',
    emoji: '🍊',
    accent_color: '#E65100',
    varieties: ['Nagpur Santra', 'Valencia'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'November – February',
    moq: '1',
    moq_unit: 'MT',
    display_order: 25,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Lemon',
    slug: 'fresh-lemon',
    category: 'Fresh Fruits',
    short_description: 'High-acid export lemons from Maharashtra and Andhra Pradesh.',
    origin: 'Maharashtra & Andhra Pradesh, India',
    emoji: '🍋',
    accent_color: '#F9A825',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'Year-round',
    moq: '500',
    moq_unit: 'Kg',
    display_order: 26,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Guava',
    slug: 'fresh-guava',
    category: 'Fresh Fruits',
    short_description: 'Allahabad Safeda and L-49 guavas, export-packed for Gulf and SE Asia.',
    origin: 'Allahabad, Uttar Pradesh & Maharashtra',
    emoji: '🟢',
    accent_color: '#66BB6A',
    varieties: ['Allahabad Safeda', 'L-49', 'Taiwan Pink'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'Year-round',
    moq: '500',
    moq_unit: 'Kg',
    display_order: 27,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Papaya',
    slug: 'fresh-papaya',
    category: 'Fresh Fruits',
    short_description: 'Red Lady and Pusa Dwarf papayas, export-graded from Maharashtra.',
    origin: 'Maharashtra & Gujarat, India',
    emoji: '🧡',
    accent_color: '#FF7043',
    varieties: ['Red Lady', 'Pusa Dwarf'],
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'Year-round',
    moq: '500',
    moq_unit: 'Kg',
    display_order: 28,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Watermelon',
    slug: 'fresh-watermelon',
    category: 'Fresh Fruits',
    short_description: 'Sweet, seedless and seeded watermelons from Andhra Pradesh.',
    origin: 'Andhra Pradesh & Karnataka, India',
    emoji: '🍉',
    accent_color: '#E53935',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'March – July',
    moq: '1',
    moq_unit: 'MT',
    display_order: 29,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fresh Muskmelon',
    slug: 'fresh-muskmelon',
    category: 'Fresh Fruits',
    short_description: 'Aromatic muskmelons from Rajasthan and UP, export-packed in ventilated boxes.',
    origin: 'Rajasthan & Uttar Pradesh, India',
    emoji: '🍈',
    accent_color: '#F9A825',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    availability: 'April – June',
    moq: '1',
    moq_unit: 'MT',
    display_order: 30,
    is_published: true,
    is_future: false,
  },

  // ==================== SPICES ====================
  {
    name: 'Turmeric Finger',
    slug: 'turmeric-finger',
    category: 'Spices',
    tagline: "Gold from Erode's black soils.",
    short_description: 'High curcumin turmeric fingers — Salem, Rajapuri, and Erode varieties.',
    full_description: "Erode, Tamil Nadu — the 'Turmeric City' — produces the world's finest turmeric with curcumin content consistently above 3.5%. Our supply chain connects directly with farmer cooperatives to deliver finger varieties machine-cleaned and polished to export specification.",
    origin: 'Erode, Tamil Nadu & Nizamabad, Telangana',
    emoji: '🟡',
    accent_color: '#D4A017',
    varieties: ['Salem Turmeric', 'Rajapuri Turmeric', 'Erode Turmeric'],
    grades: ['Premium', 'Standard', 'Commercial'],
    packaging: ['25 Kg PP Bag', '50 Kg PP Bag', 'Customized Packaging'],
    specs: [
      { label: 'Curcumin content', value: '≥ 3.5%' },
      { label: 'Moisture', value: '≤ 10%' },
      { label: 'Total ash', value: '≤ 8%' },
      { label: 'Volatile oil', value: '≥ 3.5 ml/100g' },
    ],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Organic', 'Kosher', 'Halal'],
    use_cases: ['Nutraceuticals', 'Food colouring', 'Ayurvedic formulations', 'Curry blends', 'Cosmetics'],
    related_slugs: ['turmeric-powder', 'cumin-seeds', 'red-chilli'],
    availability: 'Year-round',
    moq: '500',
    moq_unit: 'Kg',
    display_order: 31,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Turmeric Bulb',
    slug: 'turmeric-bulb',
    category: 'Spices',
    short_description: 'Turmeric bulbs with high curcumin — ideal for powder processing and planting.',
    origin: 'Erode, Tamil Nadu & Nizamabad, Telangana',
    emoji: '🟠',
    accent_color: '#D4A017',
    grades: ['Premium', 'Standard'],
    packaging: ['25 Kg PP Bag', '50 Kg PP Bag', 'Customized Packaging'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Organic'],
    related_slugs: ['turmeric-finger', 'turmeric-powder'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 32,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Turmeric Powder',
    slug: 'turmeric-powder',
    category: 'Spices',
    short_description: 'Fine-milled turmeric powder, 100–200 mesh, high curcumin content.',
    origin: 'Erode, Tamil Nadu & Nizamabad, Telangana',
    emoji: '🟡',
    accent_color: '#F9A825',
    grades: ['Premium', 'Standard'],
    packaging: ['500 gm', '1 Kg', '5 Kg', '25 Kg', 'Customized Packaging'],
    specs: [
      { label: 'Curcumin content', value: '≥ 3.5%' },
      { label: 'Moisture', value: '≤ 10%' },
      { label: 'Mesh size', value: '100–200 mesh' },
      { label: 'Colour', value: 'Bright golden yellow' },
    ],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Organic', 'Kosher', 'Halal'],
    use_cases: ['Food colouring', 'Curry powder blends', 'Nutraceuticals', 'Cosmetics'],
    related_slugs: ['turmeric-finger', 'cumin-seeds', 'coriander-seeds'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 33,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Red Chilli',
    slug: 'red-chilli',
    category: 'Spices',
    tagline: "Guntur's fire in every pod.",
    short_description: 'Bold flavour and vibrant ASTA colour from Guntur and Byadgi.',
    full_description: "Guntur district of Andhra Pradesh supplies roughly 30% of the world's chilli. We export whole dry red chillies, de-stemmed, crushed, and powder forms with ASTA colour values consistently exceeding industry benchmarks.",
    origin: 'Guntur, Andhra Pradesh & Byadgi, Karnataka',
    emoji: '🌶️',
    accent_color: '#C0392B',
    varieties: ['Teja', 'Byadgi', 'Sannam'],
    grades: ['Premium', 'Standard'],
    packaging: ['10 Kg Bag', '25 Kg Bag', '50 Kg Bag', 'Customized Packaging'],
    specs: [
      { label: 'ASTA colour value', value: '≥ 100 (up to 160+)' },
      { label: 'Moisture', value: '≤ 11%' },
      { label: 'Scoville Heat Units', value: '25,000–100,000 SHU (variety dependent)' },
      { label: 'Aflatoxin', value: '< 10 ppb' },
    ],
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000', 'EU-compliant MRL'],
    use_cases: ['Hot sauce manufacturing', 'Spice blending', 'Food colouring', 'Oleoresin extraction'],
    related_slugs: ['turmeric-finger', 'cumin-seeds', 'coriander-seeds'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 34,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Coriander Seeds',
    slug: 'coriander-seeds',
    category: 'Spices',
    short_description: 'Clean, machine-processed coriander seeds with warm citrus notes.',
    origin: 'Kota, Rajasthan & Guntur, Andhra Pradesh',
    emoji: '🌿',
    accent_color: '#5D8A3C',
    grades: ['Premium', 'Standard'],
    packaging: ['25 Kg Bag', '50 Kg Bag', 'Customized Packaging'],
    specs: [
      { label: 'Volatile oil', value: '≥ 0.3 ml/100g' },
      { label: 'Moisture', value: '≤ 10%' },
      { label: 'Extraneous matter', value: '≤ 0.1%' },
    ],
    certifications: ['APEDA', 'Spices Board India', 'FSSAI', 'ISO 22000', 'Organic'],
    use_cases: ['Spice blending', 'Curry mixes', 'Essential oil', 'Herbal teas'],
    related_slugs: ['cumin-seeds', 'turmeric-finger', 'mustard-seeds'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 35,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Cumin Seeds',
    slug: 'cumin-seeds',
    category: 'Spices',
    tagline: 'The soul of Indian cuisine.',
    short_description: 'Aromatic cumin seeds machine-cleaned to ≤ 0.1% extraneous matter.',
    origin: 'Unjha, Gujarat & Rajasthan, India',
    emoji: '🌱',
    accent_color: '#8B6914',
    grades: ['Premium', 'Standard', 'Export Quality'],
    packaging: ['25 Kg Bag', '50 Kg Bag', 'Customized Packaging'],
    specs: [
      { label: 'Volatile oil', value: '≥ 2.5 ml/100g' },
      { label: 'Moisture', value: '≤ 10%' },
      { label: 'Extraneous matter', value: '≤ 0.1%' },
    ],
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000', 'Organic'],
    use_cases: ['Spice blending', 'Essential oil extraction', 'Retail grocery', 'Food processing'],
    related_slugs: ['coriander-seeds', 'turmeric-finger', 'mustard-seeds'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 36,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fennel Seeds',
    slug: 'fennel-seeds',
    category: 'Spices',
    short_description: 'Premium fennel seeds from Gujarat with high anethole content.',
    origin: 'Gujarat & Rajasthan, India',
    emoji: '🌿',
    accent_color: '#66BB6A',
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 37,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Black Pepper',
    slug: 'black-pepper',
    category: 'Spices',
    short_description: 'High-piperine Kerala black pepper — Malabar and Tellicherry grades.',
    origin: 'Wayanad & Idukki, Kerala, India',
    emoji: '⚫',
    accent_color: '#212121',
    varieties: ['Malabar Garbled', 'Tellicherry Extra Bold'],
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000', 'Organic'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 38,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Mustard Seeds',
    slug: 'mustard-seeds',
    category: 'Spices',
    short_description: 'Yellow and black mustard seeds from Rajasthan, export machine-cleaned.',
    origin: 'Alwar & Bharatpur, Rajasthan, India',
    emoji: '🟡',
    accent_color: '#C8B400',
    varieties: ['Yellow Mustard', 'Brown Mustard', 'Black Mustard'],
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Halal'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 39,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Fenugreek Seeds',
    slug: 'fenugreek-seeds',
    category: 'Spices',
    short_description: 'Bitter-aromatic fenugreek seeds from Rajasthan, export-sortex cleaned.',
    origin: 'Rajasthan & Gujarat, India',
    emoji: '🟤',
    accent_color: '#8D6E63',
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 40,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Green Cardamom',
    slug: 'green-cardamom',
    category: 'Spices',
    short_description: 'Premium green cardamom from Idukki, Kerala — the queen of spices.',
    origin: 'Idukki, Kerala & Coorg, Karnataka',
    emoji: '🟢',
    accent_color: '#2E7D32',
    varieties: ['8 mm Bold', '7 mm Regular', '6 mm Standard'],
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000', 'Organic'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 41,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Cloves',
    slug: 'cloves',
    category: 'Spices',
    short_description: 'High-eugenol cloves from Tamil Nadu and Kerala for food and pharma use.',
    origin: 'Tamil Nadu & Kerala, India',
    emoji: '🌰',
    accent_color: '#5D4037',
    certifications: ['APEDA', 'FSSAI', 'Spices Board India', 'ISO 22000'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 42,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Bay Leaves',
    slug: 'bay-leaves',
    category: 'Spices',
    short_description: 'Sun-dried Indian bay leaves (tejpatta) from Uttarakhand and Northeast India.',
    origin: 'Uttarakhand & Meghalaya, India',
    emoji: '🍃',
    accent_color: '#558B2F',
    certifications: ['APEDA', 'FSSAI', 'Spices Board India'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 43,
    is_published: true,
    is_future: false,
  },

  // ==================== GRAINS ====================
  {
    name: 'Rice',
    slug: 'rice',
    category: 'Grains',
    short_description: 'Basmati and non-basmati rice varieties from Punjab, Haryana, and UP.',
    origin: 'Punjab, Haryana & Uttar Pradesh, India',
    emoji: '🌾',
    accent_color: '#C8882A',
    varieties: ['Basmati 1121', 'Pusa Basmati', 'Sona Masoori', 'Parboiled Rice', 'Broken Rice'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Halal'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 44,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Wheat',
    slug: 'wheat',
    category: 'Grains',
    short_description: 'Milling and durum wheat with consistent protein content from the wheat belt.',
    origin: 'Punjab, Haryana & Uttar Pradesh, India',
    emoji: '🌿',
    accent_color: '#C8882A',
    varieties: ['FAQ Milling Wheat', 'Bread Grade', 'Biscuit Grade', 'Durum Wheat'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 45,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Maize (Corn)',
    slug: 'maize-corn',
    category: 'Grains',
    short_description: 'Yellow maize for feed and starch industries from Karnataka and Andhra Pradesh.',
    origin: 'Karnataka & Andhra Pradesh, India',
    emoji: '🌽',
    accent_color: '#F9A825',
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 46,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Barley',
    slug: 'barley',
    category: 'Grains',
    short_description: 'Malting and feed grade barley from Rajasthan and Uttar Pradesh.',
    origin: 'Rajasthan & Uttar Pradesh, India',
    emoji: '🌾',
    accent_color: '#A0856C',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 47,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Jowar (Sorghum)',
    slug: 'jowar-sorghum',
    category: 'Grains',
    short_description: 'Gluten-free jowar grain for food, feed, and ethanol industries.',
    origin: 'Maharashtra & Karnataka, India',
    emoji: '🌾',
    accent_color: '#8D6E63',
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 48,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Bajra (Pearl Millet)',
    slug: 'bajra-pearl-millet',
    category: 'Grains',
    short_description: 'Nutritious pearl millet for food and feed from Rajasthan and Gujarat.',
    origin: 'Rajasthan & Gujarat, India',
    emoji: '🌾',
    accent_color: '#9E9E9E',
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 49,
    is_published: true,
    is_future: false,
  },

  // ==================== PULSES ====================
  {
    name: 'Chickpeas (Chana)',
    slug: 'chickpeas-chana',
    category: 'Pulses',
    short_description: 'Desi and Kabuli chickpeas from Madhya Pradesh and Rajasthan.',
    origin: 'Madhya Pradesh & Rajasthan, India',
    emoji: '🫘',
    accent_color: '#C8882A',
    varieties: ['Kabuli (White)', 'Desi (Brown)', 'Green Chana'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO', 'Halal'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 50,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Toor Dal',
    slug: 'toor-dal',
    category: 'Pulses',
    short_description: 'Split pigeon pea (toor dal) from Maharashtra and Karnataka.',
    origin: 'Maharashtra & Karnataka, India',
    emoji: '🫘',
    accent_color: '#D4A017',
    varieties: ['Oily Toor Dal', 'Plain Toor Dal'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO', 'Halal'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 51,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Moong Dal',
    slug: 'moong-dal',
    category: 'Pulses',
    short_description: 'Green whole moong and yellow split moong from Rajasthan and Maharashtra.',
    origin: 'Rajasthan & Maharashtra, India',
    emoji: '🫘',
    accent_color: '#66BB6A',
    varieties: ['Whole Green Moong', 'Yellow Split Moong', 'Moong Sprouts Grade'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO', 'Halal'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 52,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Urad Dal',
    slug: 'urad-dal',
    category: 'Pulses',
    short_description: 'Black gram (urad) whole and split from Madhya Pradesh and Andhra Pradesh.',
    origin: 'Madhya Pradesh & Andhra Pradesh, India',
    emoji: '🫘',
    accent_color: '#212121',
    varieties: ['Whole Urad (Black)', 'Split Urad (White)', 'Polished Urad'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 53,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Masoor Dal',
    slug: 'masoor-dal',
    category: 'Pulses',
    short_description: 'Red and brown masoor lentils, sortex cleaned, export-grade.',
    origin: 'Madhya Pradesh & Uttar Pradesh, India',
    emoji: '🫘',
    accent_color: '#E53935',
    varieties: ['Whole Brown Masoor', 'Split Red Lentil'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO', 'Halal'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 54,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Rajma (Kidney Beans)',
    slug: 'rajma-kidney-beans',
    category: 'Pulses',
    short_description: 'Red kidney beans (rajma) from Jammu and Himachal Pradesh.',
    origin: 'Jammu & Himachal Pradesh, India',
    emoji: '🫘',
    accent_color: '#B71C1C',
    varieties: ['Dark Red Kidney Bean', 'Light Red Kidney Bean', 'Chitra Rajma'],
    certifications: ['APEDA', 'FSSAI', 'ISO 22000', 'Non-GMO'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 55,
    is_published: true,
    is_future: false,
  },

  // ==================== OIL SEEDS ====================
  {
    name: 'Sesame Seeds',
    slug: 'sesame-seeds',
    category: 'Oil Seeds',
    short_description: 'Export-grade hulled and natural sesame seeds from Gujarat and Rajasthan.',
    origin: 'Gujarat, Rajasthan & Madhya Pradesh, India',
    emoji: '⚪',
    accent_color: '#B8860B',
    varieties: ['Hulled White', 'Natural White', 'Black Sesame', 'Organic Hulled'],
    specs: [
      { label: 'Oil content', value: '≥ 50%' },
      { label: 'Moisture', value: '≤ 5%' },
      { label: 'Purity', value: '≥ 99.95%' },
    ],
    certifications: ['APEDA', 'FSSAI', 'USDA Organic', 'Non-GMO', 'Halal', 'Kosher'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 56,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Groundnut (Peanut)',
    slug: 'groundnut-peanut',
    category: 'Oil Seeds',
    short_description: 'Bold and Java variety groundnuts from Saurashtra, aflatoxin tested.',
    origin: 'Saurashtra, Gujarat & Anantapur, Andhra Pradesh',
    emoji: '🥜',
    accent_color: '#A0522D',
    varieties: ['Bold 40/50', 'Bold 50/60', 'Java 60/70', 'HPS', 'Blanched'],
    specs: [
      { label: 'Aflatoxin B1', value: '< 2 ppb (EU standard)' },
      { label: 'Oil content', value: '≥ 48%' },
      { label: 'Moisture', value: '≤ 8%' },
    ],
    certifications: ['APEDA', 'FSSAI', 'EU Aflatoxin Compliant', 'Non-GMO', 'Kosher', 'Halal'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 57,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Soybean',
    slug: 'soybean',
    category: 'Oil Seeds',
    short_description: 'High-protein soybean and soybean meal from Madhya Pradesh.',
    origin: 'Madhya Pradesh & Rajasthan, India',
    emoji: '🫘',
    accent_color: '#7B8B3E',
    varieties: ['Whole Soybean', 'Soybean Meal 46%', 'Soybean Meal 48%', 'Full-Fat Soybean'],
    certifications: ['APEDA', 'FSSAI', 'Non-GMO (on request)', 'Phytosanitary', 'ISO 22000'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 58,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Mustard Seeds (Oil)',
    slug: 'mustard-seeds-oil',
    category: 'Oil Seeds',
    short_description: 'Oil-grade mustard seeds from Rajasthan for crushing and condiment production.',
    origin: 'Alwar & Bharatpur, Rajasthan, India',
    emoji: '🟡',
    accent_color: '#C8B400',
    varieties: ['Yellow Mustard', 'Brown Mustard', 'Black Mustard', 'Low-Erucic (00-grade)'],
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Halal'],
    use_cases: ['Mustard oil milling', 'Condiment production', 'Pickling'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 59,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Sunflower Seeds',
    slug: 'sunflower-seeds',
    category: 'Oil Seeds',
    short_description: 'Confectionery and oil-grade sunflower seeds from Karnataka and Maharashtra.',
    origin: 'Karnataka & Maharashtra, India',
    emoji: '🌻',
    accent_color: '#F9A825',
    varieties: ['Confectionery Grade', 'Oil Grade', 'Striped Sunflower'],
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Phytosanitary Certificate'],
    moq: '1',
    moq_unit: 'MT',
    display_order: 60,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Flax Seeds',
    slug: 'flax-seeds',
    category: 'Oil Seeds',
    short_description: 'Brown and golden flax seeds from Madhya Pradesh, high in omega-3.',
    origin: 'Madhya Pradesh & Uttar Pradesh, India',
    emoji: '🟤',
    accent_color: '#8D6E63',
    varieties: ['Brown Flax', 'Golden Flax'],
    certifications: ['APEDA', 'FSSAI', 'Non-GMO', 'Organic (select lots)'],
    moq: '500',
    moq_unit: 'Kg',
    display_order: 61,
    is_published: true,
    is_future: false,
  },

  // ==================== HERBS ====================
  {
    name: 'Mint Leaves',
    slug: 'mint-leaves',
    category: 'Herbs',
    short_description: 'Fresh Mentha arvensis and Spearmint from Uttar Pradesh and Rajasthan.',
    origin: 'Uttar Pradesh & Rajasthan, India',
    emoji: '🌿',
    accent_color: '#2E7D32',
    varieties: ['Mentha Arvensis', 'Spearmint', 'Peppermint'],
    certifications: ['APEDA', 'FSSAI', 'Organic (select lots)'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 62,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Coriander Leaves',
    slug: 'coriander-leaves',
    category: 'Herbs',
    short_description: 'Fresh green coriander (dhania) leaves from Gujarat and Maharashtra.',
    origin: 'Gujarat & Maharashtra, India',
    emoji: '🌿',
    accent_color: '#388E3C',
    certifications: ['APEDA', 'FSSAI', 'Phytosanitary Certificate'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 63,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Curry Leaves',
    slug: 'curry-leaves',
    category: 'Herbs',
    short_description: 'Fresh and dried curry leaves from Tamil Nadu and Andhra Pradesh.',
    origin: 'Tamil Nadu & Andhra Pradesh, India',
    emoji: '🍃',
    accent_color: '#558B2F',
    varieties: ['Fresh Curry Leaves', 'Dried Curry Leaves'],
    certifications: ['APEDA', 'FSSAI', 'Organic (select lots)'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 64,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Moringa Leaves',
    slug: 'moringa-leaves',
    category: 'Herbs',
    short_description: 'Organic moringa (drumstick) leaves — fresh and dried powder — from Tamil Nadu.',
    origin: 'Tamil Nadu & Andhra Pradesh, India',
    emoji: '🌱',
    accent_color: '#1B5E20',
    varieties: ['Fresh Leaves', 'Dried Powder', 'Moringa Leaf Extract'],
    certifications: ['APEDA', 'FSSAI', 'Organic', 'Halal', 'Kosher'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 65,
    is_published: true,
    is_future: false,
  },
  {
    name: 'Tulsi Leaves',
    slug: 'tulsi-leaves',
    category: 'Herbs',
    short_description: 'Sacred basil (tulsi) leaves for herbal teas and nutraceuticals.',
    origin: 'Uttar Pradesh & Madhya Pradesh, India',
    emoji: '🌿',
    accent_color: '#2E7D32',
    varieties: ['Rama Tulsi', 'Krishna Tulsi', 'Vana Tulsi'],
    certifications: ['APEDA', 'FSSAI', 'Organic', 'Kosher'],
    moq: '100',
    moq_unit: 'Kg',
    display_order: 66,
    is_published: true,
    is_future: false,
  },

  // ==================== FUTURE PRODUCTS ====================
  { name: 'Dry Fruits', slug: 'dry-fruits', category: 'Future', display_order: 100, is_published: false, is_future: true },
  { name: 'Dehydrated Onion', slug: 'dehydrated-onion', category: 'Future', display_order: 101, is_published: false, is_future: true },
  { name: 'Dehydrated Garlic', slug: 'dehydrated-garlic', category: 'Future', display_order: 102, is_published: false, is_future: true },
  { name: 'Dehydrated Vegetables', slug: 'dehydrated-vegetables', category: 'Future', display_order: 103, is_published: false, is_future: true },
  { name: 'Pickles', slug: 'pickles', category: 'Future', display_order: 104, is_published: false, is_future: true },
  { name: 'Papad', slug: 'papad', category: 'Future', display_order: 105, is_published: false, is_future: true },
  { name: 'Spice Blends', slug: 'spice-blends', category: 'Future', display_order: 106, is_published: false, is_future: true },
  { name: 'Organic Products', slug: 'organic-products', category: 'Future', display_order: 107, is_published: false, is_future: true },
  { name: 'Tea', slug: 'tea', category: 'Future', display_order: 108, is_published: false, is_future: true },
  { name: 'Coffee', slug: 'coffee', category: 'Future', display_order: 109, is_published: false, is_future: true },
  { name: 'Jaggery', slug: 'jaggery', category: 'Future', display_order: 110, is_published: false, is_future: true },
  { name: 'Sugar', slug: 'sugar', category: 'Future', display_order: 111, is_published: false, is_future: true },
  { name: 'Coconut Products', slug: 'coconut-products', category: 'Future', display_order: 112, is_published: false, is_future: true },
  { name: 'Animal Feed Products', slug: 'animal-feed-products', category: 'Future', display_order: 113, is_published: false, is_future: true },
  { name: 'Herbal Products', slug: 'herbal-products', category: 'Future', display_order: 114, is_published: false, is_future: true },
  { name: 'Value Added Food Products', slug: 'value-added-food-products', category: 'Future', display_order: 115, is_published: false, is_future: true },
]

async function seed() {
  console.log(`Seeding ${products.length} products...`)

  const { error: deleteError } = await supabase.from('products').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  if (deleteError) {
    console.error('Error clearing products:', deleteError)
    process.exit(1)
  }

  const insertData = products.map((p) => ({
    name: p.name,
    slug: p.slug,
    category: p.category,
    tagline: p.tagline ?? null,
    short_description: p.short_description ?? null,
    full_description: p.full_description ?? null,
    origin: p.origin ?? null,
    emoji: p.emoji ?? null,
    accent_color: p.accent_color ?? null,
    images: [],
    specs: p.specs ?? [],
    varieties: p.varieties ?? [],
    grades: p.grades ?? [],
    packaging: p.packaging ?? [],
    certifications: p.certifications ?? [],
    use_cases: p.use_cases ?? [],
    related_slugs: p.related_slugs ?? [],
    availability: p.availability ?? null,
    moq: p.moq ?? null,
    moq_unit: p.moq_unit ?? null,
    display_order: p.display_order,
    is_published: p.is_published,
    is_future: p.is_future,
  }))

  const { error } = await supabase.from('products').insert(insertData)
  if (error) {
    console.error('Seed error:', error)
    process.exit(1)
  }

  console.log(`✅ Seeded ${products.length} products successfully.`)
}

seed()
